# Site settings
title: GOUTENOIR Samuel
email: sam uel.goute noir@ gmail.c om
description: > # this means to ignore newlines until "baseurl:"
  Trololololo !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mussblatter.github.io/" # the base hostname & protocol for your site
twitter_username: Mussblatter
github_username:  Mussblatter

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Electronic Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
