# Site settings
title: GOUTENOIR Samuel
email: sam uel.goute noir@ gmail.c om
description: > # this means to ignore newlines until "baseurl:"
   Ingénieur en génie électrique et systèmes de commande, je suis passionné par la domotique, la robotique et tout ce qui se rapporte à l'automatisme.
   Je suis curieux, polyvalent et jʼapprends vite. Je travaille souvent de manière autodidacte ce qui me permet d'être autonome et me rend adaptable à toutes situations.

J'aime le code propre et rigoureux. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mussblatter.github.io/" # the base hostname & protocol for your site
twitter_username: Mussblatter
github_username:  Mussblatter

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Electronic Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
